import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,bodypage,nav
}: {
    children: React.ReactNode;
    bodypage: React.ReactNode;
    nav: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{nav}</div>
        <div>{bodypage}</div>
        {children}
      </body>
    </html>
  )
}
